name: Check for OpenAPI files from different Geoportals
on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - uses: actions/checkout@v3
      - run: go run .
        working-directory: api-finder
