name: Check JSON-files

on:
  push:
    paths:
      - "*.json"

  pull_request:
    paths:
      - "*.json"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-lint
        uses: ocular-d/json-linter@0.0.2
